language: python

branches:
  only:
    - master
    - dev

dist: xenial

addons:
  apt:
    packages: ['gfortran']

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

before_script: make install

script: make tests